# Generated by Django 4.2.1 on 2023-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('project', models.TextField()),
                ('project_duration', models.CharField(max_length=255)),
                ('tractions', models.TextField()),
                ('startup_stage', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('funds_investment', models.TextField()),
                ('pitch_deck', models.FileField(upload_to='corporate_pitch_decks/')),
                ('financial_model', models.FileField(upload_to='corporate_financial_models/')),
                ('cac_documents', models.FileField(upload_to='corporate_cac_documents/')),
                ('valuation_report', models.FileField(upload_to='corporate_valuation_reports/')),
                ('business_registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElearningAreaOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElearningContactOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElearningInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('state_region', models.CharField(max_length=255)),
                ('interest', models.TextField()),
                ('sector', models.TextField()),
                ('additional_info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin_profile', models.URLField()),
                ('facebook_profile', models.URLField()),
                ('instagram_handle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MentorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('professional_title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('sector', models.TextField()),
                ('area_of_expertise', models.TextField()),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectorOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SMERegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('project', models.TextField()),
                ('project_duration', models.CharField(max_length=255)),
                ('tractions', models.TextField()),
                ('startup_stage', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('funds_investment', models.TextField()),
                ('pitch_deck', models.FileField(upload_to='sme_pitch_decks/')),
                ('financial_model', models.FileField(upload_to='sme_financial_models/')),
                ('cac_documents', models.FileField(upload_to='sme_cac_documents/')),
                ('valuation_report', models.FileField(upload_to='sme_valuation_reports/')),
                ('business_registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TouristInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TouristRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('additional_info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField()),
                ('facebook_profile', models.URLField()),
                ('instagram_handle', models.CharField(max_length=255)),
                ('interests', models.ManyToManyField(to='shareafric_app.touristinterest')),
                ('sector_of_interest', models.ManyToManyField(to='shareafric_app.sectorofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='ElearningRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('interests_to_communicate', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('agree_to_newsletters', models.BooleanField(default=False)),
                ('areas_of_study', models.ManyToManyField(to='shareafric_app.elearningareaofstudy')),
                ('contact_options', models.ManyToManyField(to='shareafric_app.elearningcontactoption')),
                ('interests', models.ManyToManyField(to='shareafric_app.elearninginterest')),
            ],
        ),
    ]
