# Generated by Django 4.2.1 on 2023-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateregistration',
            name='business_registration_date',
            field=models.CharField(max_length=20),
        ),
    ]
