# Generated by Django 4.2.1 on 2023-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0002_alter_corporateregistration_business_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorregistration',
            old_name='area_of_expertise',
            new_name='area_of_expertise_and_title',
        ),
        migrations.RenameField(
            model_name='mentorregistration',
            old_name='first_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='mentorregistration',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='mentorregistration',
            name='region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smeregistration',
            name='business_registration_date',
            field=models.CharField(max_length=20),
        ),
    ]
