# Generated by Django 4.2.1 on 2023-06-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0003_rename_area_of_expertise_mentorregistration_area_of_expertise_and_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorregistration',
            name='professional_title',
        ),
    ]
