# Generated by Django 4.2.1 on 2023-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0006_remove_elearningregistration_agree_to_newsletters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearningregistration',
            name='areas_of_study',
        ),
        migrations.AddField(
            model_name='elearningregistration',
            name='areas_of_study',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
