# Generated by Django 4.2.1 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0008_remove_elearningregistration_elearning_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearningregistration',
            name='elearning_interest',
        ),
        migrations.AddField(
            model_name='elearningregistration',
            name='elearning_interest',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
