# Generated by Django 4.2.1 on 2023-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0009_remove_elearningregistration_elearning_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningregistration',
            name='contact_options',
            field=models.CharField(blank=True, choices=[('phone', 'With Phone'), ('email', 'With Email')], max_length=20, null=True),
        ),
    ]
