# Generated by Django 4.2.1 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0010_alter_elearningregistration_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='theTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='webImages')),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='webImages')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('welcome_text', models.CharField(max_length=255)),
                ('sub_welcome_text', models.CharField(max_length=255)),
                ('about_us_short', models.TextField()),
                ('about_us_long', models.TextField()),
                ('about_us_image', models.FileField(upload_to='webImages')),
            ],
        ),
    ]
