# Generated by Django 4.2.1 on 2023-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareafric_app', '0011_theteam_webdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_font_awesome', models.CharField(max_length=255)),
                ('service_title', models.CharField(max_length=50)),
                ('service_brief_description', models.CharField(max_length=100)),
                ('service_link', models.URLField(max_length=100)),
            ],
        ),
    ]
